name: $(Build.SourceBranchName)_$(Build.Reason)_$(devops_buildNumber)

pr:
  branches:
    include:
    - master
    - dev

trigger:
  branches:
    include:
    - dev
    - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  devops_buildNumber: $[counter(format(''), 1500)]
  APPVEYOR_REPO_BRANCH: $[coalesce(variables['System.PullRequest.TargetBranch'], variables['Build.SourceBranchName'])]
  APPVEYOR_REPO_COMMIT: $(Build.SourceVersion)

steps:
- pwsh: |
    Write-Host "Target branch: '$(APPVEYOR_REPO_BRANCH)'"
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
- task: NuGetToolInstaller@1
  inputs:
    versionSpec:
- task: AzureCLI@2
  displayName: Login via Azure CLI to acquire access token
  inputs:
    azureSubscription: $(E2ETestServiceConnectionName)
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      # acquire access token from Azure CLI and export it to AZURE_MANAGEMENT_ACCESS_TOKEN
      $accessToken = (az account get-access-token --query "accessToken" | % { $_.Trim('"') })
      echo "##vso[task.setvariable variable=azure_management_access_token]$accessToken"
- pwsh: | 
    .\build.ps1
  env:
    AzureBlobSigningConnectionString: $(AzureBlobSigningConnectionString)
    BuildArtifactsStorage: $(BuildArtifactsStorage)
    DURABLE_STORAGE_CONNECTION: $(DURABLE_STORAGE_CONNECTION)
    TELEMETRY_INSTRUMENTATION_KEY: $(TELEMETRY_INSTRUMENTATION_KEY)
  displayName: 'Executing build script'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()
- task: EsrpCodeSigning@1
  inputs:
    ConnectedServiceName: 'ESRP Service'
    FolderPath: '$(Build.Repository.LocalPath)\artifacts'
    Pattern: '*.msi'
    signConfigType: 'inlineSignParams'
    inlineOperation: |
      [
              {
                  "KeyCode" : "CP-230012",
                  "OperationCode" : "SigntoolSign",
                  "Parameters" : {
                      "OpusName" : "Microsoft",
                      "OpusInfo" : "http://www.microsoft.com",
                      "FileDigest" : "/fd \"SHA256\"",
                      "PageHash" : "/NPH",
                      "TimeStamp" : "/tr \"http://rfc3161.gtm.corp.microsoft.com/TSS/HttpTspServer\" /td sha256"
                  },
                  "ToolName" : "sign",
                  "ToolVersion" : "1.0"
              },
              {
                  "KeyCode" : "CP-230012",
                  "OperationCode" : "SigntoolVerify",
                  "Parameters" : {},
                  "ToolName" : "sign",
                  "ToolVersion" : "1.0"
              }
          ]
    SessionTimeout: '60'
    MaxConcurrency: '50'
    MaxRetryAttempts: '5'  
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)\artifacts'
    Contents: |
      Azure.Functions.Cli.*
      func-cli*.msi
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
